module.exports = (elastic, config) => ([
  require('./redirects').random(),
  require('./redirects').medicine(),
  require('./home')(),
  require('./search')(elastic, config),
  require('./public')(),
  require('./archive')(elastic, config),
  require('./object')(elastic, config),
  require('./person')(elastic, config),
  require('./autocomplete')(elastic, config),
  require('./sitemap')(config),
  require('./analytics')(),
  require('./museum').scm(),
  require('./museum').msi(),
  require('./museum').nmem(),
  require('./museum').nrm(),
  require('./api')(elastic, config),
  require('./iiif')(elastic, config),
  require('./object-id')(elastic, config),
  require('./robot')(),
  require('./articles')(),
  require('./wiki')(config),
  require('./iris')(elastic, config),
  require('./embed').rotational(elastic, config),
  require('./embed').rotationalDirect(),
  require('./about')(),
  require('./stats')(elastic, config),
  require('./categories')(elastic, config),
  require('./imgtags')(elastic, config)
]);
