'use strict';

// Aggregate metrics for the admin dashboard — top-level counts, cost totals,
// activity over time, flag and skip-reason breakdowns.
//
// Approach: one full-table scan, aggregated incrementally page-by-page so
// peak memory stays at ~1MB (one DynamoDB page). Result cached in-process
// for 5 minutes. Both the main list page's headline strip and the full
// dashboard page read from this cache via getStats().
//
// At current scale (<25k records) a scan is cheap and the cache hit rate
// is very high. When/if volume grows past ~250k records the migration path
// is a denormalised STATS item updated on writes — not needed yet.

const modelsRegistry = require('./models');
const subjectStatus = require('./subject-status');

// 15 seconds — short enough that admin changes (hide/regenerate/flag/etc.)
// are reflected on the dashboard within a single browsing beat, long enough
// that rapid-click sessions don't thrash the DynamoDB scan. Raise if scan
// cost ever becomes visible (not imminent at <25k records).
const TTL_MS = 15 * 1000;
const SCAN_PAGE_SIZE = 500;

// Single-entry cache. Not a keyed map — one global aggregate, replaced on
// each recompute, so memory is O(1) regardless of load.
let cached = null; // { value, computedAt }
let inFlight = null; // Promise, so concurrent callers share one scan

async function getStats (dynamo, config) {
  const now = Date.now();
  if (cached && (now - cached.computedAt) < TTL_MS) {
    return cached.value;
  }
  if (inFlight) return inFlight;
  inFlight = compute(dynamo, config)
    .then(function (value) {
      cached = { value, computedAt: Date.now() };
      return value;
    })
    .finally(function () { inFlight = null; });
  return inFlight;
}

// Exposed for tests and for the admin "force refresh" path if ever needed.
function invalidate () {
  cached = null;
}

async function compute (dynamo, config) {
  if (!dynamo.isReady()) {
    return emptyStats();
  }

  const acc = makeAccumulator(config);

  let lastKey = null;
  do {
    const page = await dynamo.scan(SCAN_PAGE_SIZE, lastKey);
    (page.items || []).forEach(function (item) { ingest(item, acc); });
    lastKey = page.lastKey;
  } while (lastKey);

  return finalise(acc);
}

// Shape of the accumulator. Plain object so aggregation is fast and
// memory-small. Finalised into the public shape by finalise().
function makeAccumulator (config) {
  return {
    config,
    // Biography canonical items
    totals: {
      biographies: 0,
      live: 0,
      flagged: 0,
      hidden: 0,
      insufficient_data: 0,
      // Policy-driven suppression — records with content that the public
      // route returns 204 for because the subject is living and the
      // aiBiographyIncludeLiving flag is off. Tracked per source status
      // so the UI can split "live but hidden" from "flagged but hidden".
      liveSuppressed: 0,
      flaggedSuppressed: 0,
      // Total records that HAVE content but aren't on the public site, via
      // any mechanism: manual hide, or living-person suppression on a live
      // or flagged record. Excludes `insufficient_data` — those records
      // have no content, so they aren't "hidden" in the sense a curator
      // would recognise.
      hiddenFromPublic: 0
    },
    subjects: {
      person: 0,
      company: 0,
      organisation: 0,
      unknown: 0
    },
    // Cost aggregation — accumulated separately per "kind" (biography
    // generation vs AI review of an existing biography) so the dashboard
    // can show:
    //   - a combined total (what's been spent overall)
    //   - a per-kind breakdown (where the spend is going)
    //   - a per-model breakdown within each kind (which models were used)
    // Reviews use the configured premium model (Opus etc.) and cost an
    // order of magnitude more per call than biography generations
    // (Sonnet), so excluding them from totals would meaningfully
    // under-report spend. byKind keeps the two streams visible without
    // losing the combined number.
    // Unknown-model entries (records generated by a model that has
    // since been retired from the registry) are tracked separately
    // per-kind so they aren't silently dropped.
    costs: {
      byKind: {
        biography: { count: 0, lifetime: 0, thisMonth: 0, last30Days: 0 },
        review: { count: 0, lifetime: 0, thisMonth: 0, last30Days: 0 }
      },
      byModel: Object.create(null), // biography models: id → { cost, count }
      reviewsByModel: Object.create(null), // review models: id → { cost, count }
      unknownModelCount: 0, // biographies with unrecognised model
      reviewUnknownModelCount: 0 // reviews with unrecognised model
    },
    // Activity — records per ISO week over the last 8 weeks, plus this/last
    // week counts.
    activity: {
      thisWeek: 0,
      lastWeek: 0,
      byWeek: Object.create(null) // weekStartIso → count
    },
    // Public flag aggregate items. Pending counters are resolved in
    // finalise() — we need each record's canonical `status` to decide
    // whether its pending reports still belong in the "inbox" headline.
    // Raw flag items are collected here, aggregated after the scan when
    // both biography statuses and flag items are known.
    flags: {
      lifetimeReports: 0,
      byReason: Object.create(null), // reason → lifetime count
      // Resolved in finalise():
      pendingReports: 0,
      pendingAcrossRecords: 0
    },
    // PK → status  (from canonical BIOGRAPHY items, for status lookup in finalise)
    biographyStatusByPk: Object.create(null),
    // PK → raw FLAGS item  (kept until finalise so pending counts can be
    // scoped by the corresponding biography's current status)
    publicFlagsByPk: Object.create(null),
    // Staff activity
    staff: {
      flaggedRecords: new Set(), // PKs with any STAFF_FLAG item
      notes: 0
    },
    // Why records land at insufficient_data
    skipReasons: Object.create(null), // reason → count

    // ---------------------------------------------------------------
    // v2 source-tagged pipeline metrics (Task 53).
    //
    // recordsWithSentences   how many BIOGRAPHY items have a sentences[]
    //                        array — i.e. were produced by the v2 writer.
    //                        Distinct from totals.biographies (which
    //                        counts legacy + v2 records).
    // sourceTagCounts        distribution of source tags across every
    //                        sentence in the collection. Individual
    //                        `llm:validated:<toolname>` variants collapse
    //                        under a single 'llm:validated' key — the tool
    //                        name is not useful at the dashboard level.
    // verificationCandidates aggregate counts across every record's
    //                        `verificationCandidates` block (populated by
    //                        the v2 writer via parse-source-tagged-response).
    //                        estimatedExternalValidationCost sums the per-
    //                        record cost the writer projected — the
    //                        "what would running batch external
    //                        verification on every candidate cost right
    //                        now?" number.
    // recordsWithOpenFindings PKs of records with at least one review
    //                        finding whose resolution === 'pending'.
    //                        Set, size taken at finalise time.
    // recordsWithCuratorDecisions PKs with a CURATOR_DECISIONS item
    //                        that has at least one non-empty array
    //                        (approvals / rejections / clarifications).
    //                        Set, size taken at finalise time.
    // ---------------------------------------------------------------
    v2: {
      recordsWithSentences: 0,
      sourceTagCounts: Object.create(null),
      verificationCandidates: {
        generalKnowledge: 0,
        contextualising: 0,
        lowConfidenceInferred: 0,
        estimatedExternalValidationCost: 0
      },
      recordsWithOpenFindings: new Set(),
      recordsWithCuratorDecisions: new Set()
    }
  };
}

function ingest (item, acc) {
  if (!item) return;
  if (item.entityType === 'BIOGRAPHY') {
    ingestBiography(item, acc);
  } else if (item.entityType === 'PUBLIC_FLAG') {
    ingestPublicFlag(item, acc);
  } else if (item.entityType === 'STAFF_FLAG') {
    acc.staff.flaggedRecords.add(item.PK);
  } else if (item.entityType === 'STAFF_NOTE') {
    acc.staff.notes += 1;
  } else if (item.entityType === 'REVIEW') {
    ingestReview(item, acc);
  } else if (item.entityType === 'CURATOR_DECISIONS') {
    ingestCuratorDecisions(item, acc);
  }
  // Everything else is ignored.
}

function ingestBiography (item, acc) {
  acc.totals.biographies += 1;
  if (item.status && Object.prototype.hasOwnProperty.call(acc.totals, item.status)) {
    acc.totals[item.status] += 1;
  }
  // Remember status per PK so finalise() can scope pending-report counts to
  // records still publicly visible (live / flagged). Records with status
  // hidden or insufficient_data drop out of the headline "inbox".
  acc.biographyStatusByPk[item.PK] = item.status;

  // Hidden-from-public accounting. Three routes to invisibility on the
  // public site (all require biography content to actually count):
  //   1. status=hidden            — manually hidden by a staff member
  //   2. living-person policy on status=live
  //   3. living-person policy on status=flagged
  // `hiddenFromPublic` is the union, used by the Live card's hint line
  // to answer "how many records have content but aren't on site?". The
  // two *Suppressed counters let the tooltip break that number down by
  // reason. `insufficient_data` records are deliberately excluded —
  // they don't have content, so "hidden" isn't the right word for them.
  //
  // The policy check itself lives in subject-status.isSuppressedOnPublicSite
  // so the three call sites (public route, admin visibility helper, this
  // dashboard aggregator) agree on one rule — in particular, companies /
  // organisations are always eligible regardless of `isLiving`.
  const config = acc.config;
  const policySuppresses = subjectStatus.isSuppressedOnPublicSite(item.subjectStatus, config);
  if (item.status === 'live' && policySuppresses) {
    acc.totals.liveSuppressed += 1;
  }
  if (item.status === 'flagged' && policySuppresses) {
    acc.totals.flaggedSuppressed += 1;
  }
  if (item.biographyHtml) {
    if (item.status === 'hidden') {
      acc.totals.hiddenFromPublic += 1;
    } else if ((item.status === 'live' || item.status === 'flagged') && policySuppresses) {
      acc.totals.hiddenFromPublic += 1;
    }
  }

  // Subject breakdown. subjectType was added mid-project so older records
  // may lack it — those count as 'unknown' rather than being dropped.
  const subjectType = item.subjectStatus && item.subjectStatus.subjectType;
  if (subjectType && Object.prototype.hasOwnProperty.call(acc.subjects, subjectType)) {
    acc.subjects[subjectType] += 1;
  } else {
    acc.subjects.unknown += 1;
  }

  // Cost — only records with a model from the current registry contribute
  // to the totals. Unknown-model (retired models / legacy) records are
  // tallied separately so we don't silently misrepresent spend.
  // Costs flow into the `biography` bucket of byKind; combined totals
  // are computed in finalise() so reviews can be folded in alongside.
  if (item.model && item.inputTokens != null && item.outputTokens != null) {
    const cost = modelsRegistry.calculateCost(item.model, item.inputTokens, item.outputTokens, acc.config.aiBiographyGbpPerUsd);
    if (cost) {
      const bio = acc.costs.byKind.biography;
      bio.lifetime += cost.perBio;
      bio.count += 1;
      const generatedAt = item.generatedAt ? new Date(item.generatedAt) : null;
      if (generatedAt && !Number.isNaN(generatedAt.getTime())) {
        if (isSameCalendarMonth(generatedAt, new Date())) {
          bio.thisMonth += cost.perBio;
        }
        if (withinDays(generatedAt, 30)) {
          bio.last30Days += cost.perBio;
        }
      }
      const modelAcc = acc.costs.byModel[item.model] || (acc.costs.byModel[item.model] = { cost: 0, count: 0 });
      modelAcc.cost += cost.perBio;
      modelAcc.count += 1;
    } else {
      acc.costs.unknownModelCount += 1;
    }
  }

  // Activity — bucket by ISO-week start. Only last 8 weeks (including this
  // week) are kept; older buckets are dropped at finalise time.
  const generatedAt = item.generatedAt ? new Date(item.generatedAt) : null;
  if (generatedAt && !Number.isNaN(generatedAt.getTime())) {
    if (withinDays(generatedAt, 7)) acc.activity.thisWeek += 1;
    else if (withinDays(generatedAt, 14)) acc.activity.lastWeek += 1;
    const weekStart = startOfIsoWeek(generatedAt).toISOString().slice(0, 10);
    acc.activity.byWeek[weekStart] = (acc.activity.byWeek[weekStart] || 0) + 1;
  }

  // Skip reasons — only for records that actually ended up skipped.
  if (item.status === 'insufficient_data' && item.skipReason) {
    // Collapse to the prefix up to the first em-dash or open-paren so near-
    // identical reasons ("Low confidence (3/10) …", "Low confidence (2/10) …")
    // bucket together.
    const key = item.skipReason.split(/[—(]/)[0].trim();
    acc.skipReasons[key] = (acc.skipReasons[key] || 0) + 1;
  }

  // v2 pipeline metrics — sentence source-tag distribution +
  // verification-candidate aggregation. Legacy (v1) records don't have a
  // sentences[] array and skip these blocks silently.
  if (Array.isArray(item.sentences) && item.sentences.length > 0) {
    acc.v2.recordsWithSentences += 1;
    item.sentences.forEach(function (s) {
      if (!s || typeof s.source !== 'string') return;
      // Collapse llm:validated:<toolname> variants under one key. The
      // specific tool that validated a sentence isn't useful at
      // collection-level; per-tool cost accounting sits under the
      // external-verify cache stats if we ever surface those.
      const key = s.source.indexOf('llm:validated:') === 0 ? 'llm:validated' : s.source;
      acc.v2.sourceTagCounts[key] = (acc.v2.sourceTagCounts[key] || 0) + 1;
    });
  }
  const vc = item.verificationCandidates;
  if (vc && typeof vc === 'object') {
    acc.v2.verificationCandidates.generalKnowledge += vc.generalKnowledgeCount || 0;
    acc.v2.verificationCandidates.contextualising += vc.contextualisingCount || 0;
    acc.v2.verificationCandidates.lowConfidenceInferred += vc.lowConfidenceInferredCount || 0;
    acc.v2.verificationCandidates.estimatedExternalValidationCost += vc.estimatedExternalValidationCost || 0;
  }
}

// Reviews are AI fact-checks of an existing biography, produced by the
// configured premium model (Opus etc.). Each call costs roughly an order
// of magnitude more than a biography generation (Sonnet), so they're a
// meaningful slice of total AI spend. We bucket them under
// acc.costs.byKind.review so the dashboard can split spend by kind, and
// also keep a per-model tally so the Spend panel can break out which
// review models were used.
//
// Timestamp source: REVIEW items use `createdAt` (set by addReview in
// biography-store.js); biographies use `generatedAt`. Both are ISO
// strings.
function ingestReview (item, acc) {
  // v2 REVIEW# items carry findings[] — check ONCE per item whether at
  // least one has resolution='pending'. Add the parent PK to the open-
  // findings set so multiple reviews on the same subject don't
  // double-count in the headline metric.
  if (Array.isArray(item.findings)) {
    for (const f of item.findings) {
      if (f && f.resolution === 'pending') {
        acc.v2.recordsWithOpenFindings.add(item.PK);
        break;
      }
    }
  }

  // Legacy v1 review + v2 review cost accounting is identical — both
  // use inputTokens + outputTokens + a model. v2 review-store uses
  // `reviewerModel` (matches its schema) whereas legacy v1 uses
  // `reviewModel`. Accept either so v2 reviews cost-account correctly
  // without a schema migration.
  const modelId = item.reviewerModel || item.reviewModel;
  if (!modelId || item.inputTokens == null || item.outputTokens == null) {
    // Missing the data we need to cost it. Skip silently — older review
    // schemas may lack these fields and shouldn't crash the aggregator.
    return;
  }
  const cost = modelsRegistry.calculateCost(modelId, item.inputTokens, item.outputTokens, acc.config.aiBiographyGbpPerUsd);
  if (!cost) {
    acc.costs.reviewUnknownModelCount += 1;
    return;
  }
  const review = acc.costs.byKind.review;
  review.lifetime += cost.perBio;
  review.count += 1;
  // v1 review-store used `createdAt`; v2 review-store uses `reviewedAt`.
  // Both are ISO strings — take whichever is present.
  const ts = item.reviewedAt || item.createdAt;
  const createdAt = ts ? new Date(ts) : null;
  if (createdAt && !Number.isNaN(createdAt.getTime())) {
    if (isSameCalendarMonth(createdAt, new Date())) {
      review.thisMonth += cost.perBio;
    }
    if (withinDays(createdAt, 30)) {
      review.last30Days += cost.perBio;
    }
  }
  const modelAcc = acc.costs.reviewsByModel[modelId] || (acc.costs.reviewsByModel[modelId] = { cost: 0, count: 0 });
  modelAcc.cost += cost.perBio;
  modelAcc.count += 1;
}

// v2 CURATOR_DECISIONS singleton per subject. Records a PK as "has
// curator work" if any of the three action arrays contain at least
// one entry. Empty items (all three arrays empty) are ignored — those
// happen when curator-decisions-store.ensureItem() creates a blank
// singleton before the first action lands.
function ingestCuratorDecisions (item, acc) {
  const anyApprovals = Array.isArray(item.approvals) && item.approvals.length > 0;
  const anyRejections = Array.isArray(item.rejections) && item.rejections.length > 0;
  const anyClarifications = Array.isArray(item.clarifications) && item.clarifications.length > 0;
  if (anyApprovals || anyRejections || anyClarifications) {
    acc.v2.recordsWithCuratorDecisions.add(item.PK);
  }
}

function ingestPublicFlag (item, acc) {
  const total = item.totalFlags || 0;
  acc.flags.lifetimeReports += total;
  // Lifetime per-reason counts are always aggregated — they're historical,
  // not "inbox" signals, and scoping them by status would make lifetime
  // totals jump around as records change status.
  Object.keys(item).forEach(function (k) {
    if (k.indexOf('count_') === 0 && k.indexOf('count_pending_') !== 0) {
      const reason = k.slice('count_'.length);
      acc.flags.byReason[reason] = (acc.flags.byReason[reason] || 0) + (item[k] || 0);
    }
  });
  // Pending counts are resolved in finalise(), once we know the status of
  // each FLAGS item's sibling BIOGRAPHY — hidden records drop out of the
  // pending-reports "inbox" count.
  acc.publicFlagsByPk[item.PK] = item;
}

function finalise (acc) {
  // Derived: records actually visible to the public (status=live minus
  // those suppressed by the living-person policy). Computed once here so
  // the Live-biographies headline card can show a number that matches
  // what visitors actually see on the site.
  acc.totals.livePublic = Math.max(0, acc.totals.live - acc.totals.liveSuppressed);

  // Resolve pending public-report counts scoped to records that are still
  // publicly visible. The dashboard "Pending reports" card is meant as an
  // inbox — items needing staff attention right now. Once a record is
  // hidden, the public-harm signal is resolved (visitors can't see it
  // anymore) so its pending reports drop out of the headline count. The
  // lifetime totals + per-record report columns on the list are unaffected
  // and still surface the reports when drilling into the Hidden tab.
  Object.keys(acc.publicFlagsByPk).forEach(function (pk) {
    const item = acc.publicFlagsByPk[pk];
    const pending = item.pendingFlags || 0;
    if (pending <= 0) return;
    const status = acc.biographyStatusByPk[pk];
    const publiclyVisible = status === 'live' || status === 'flagged';
    if (!publiclyVisible) return;
    acc.flags.pendingReports += pending;
    acc.flags.pendingAcrossRecords += 1;
  });

  // Convert per-model maps → sorted arrays (most-used first). Same shape
  // for biographies and reviews — the dashboard renders them in
  // separate sub-sections, but they share rendering logic.
  const byModel = sortedModelBreakdown(acc.costs.byModel);
  const reviewsByModel = sortedModelBreakdown(acc.costs.reviewsByModel);

  // Combined totals across both kinds. The headline-strip card and the
  // top of the Spend panel show these so "spend this month" matches
  // total Anthropic billable cost regardless of what triggered it.
  const bio = acc.costs.byKind.biography;
  const review = acc.costs.byKind.review;
  const combinedLifetime = bio.lifetime + review.lifetime;
  const combinedThisMonth = bio.thisMonth + review.thisMonth;
  const combinedLast30 = bio.last30Days + review.last30Days;

  // Build the last 8 ISO-weeks (oldest → newest) so the bar chart renders
  // left-to-right in time order, with zero counts for weeks that had no
  // generation activity.
  const byWeek = [];
  for (let i = 7; i >= 0; i--) {
    const d = new Date();
    d.setUTCDate(d.getUTCDate() - (i * 7));
    const weekStart = startOfIsoWeek(d).toISOString().slice(0, 10);
    byWeek.push({
      weekStart,
      count: acc.activity.byWeek[weekStart] || 0
    });
  }

  const topSkipReasons = Object.keys(acc.skipReasons)
    .map(function (r) { return { reason: r, count: acc.skipReasons[r] }; })
    .sort(function (a, b) { return b.count - a.count; })
    .slice(0, 6);

  const topFlagReasons = Object.keys(acc.flags.byReason)
    .map(function (r) { return { reason: r, count: acc.flags.byReason[r] }; })
    .sort(function (a, b) { return b.count - a.count; })
    .filter(function (r) { return r.count > 0; });

  return {
    computedAt: new Date().toISOString(),
    totals: acc.totals,
    subjects: acc.subjects,
    costs: {
      // Combined totals (biographies + reviews) — what the headline
      // strip and the top of the Spend panel surface.
      lifetime: combinedLifetime,
      lifetimeFormatted: formatGbp(combinedLifetime),
      thisMonth: combinedThisMonth,
      thisMonthFormatted: formatGbp(combinedThisMonth),
      last30Days: combinedLast30,
      last30DaysFormatted: formatGbp(combinedLast30),
      // Per-kind breakdown — shown on the dashboard so it's visible
      // what share of spend is biography generation vs review.
      byKind: [
        {
          kind: 'biography',
          label: 'Biographies',
          count: bio.count,
          lifetime: bio.lifetime,
          lifetimeFormatted: formatGbp(bio.lifetime),
          thisMonth: bio.thisMonth,
          thisMonthFormatted: formatGbp(bio.thisMonth),
          last30Days: bio.last30Days,
          last30DaysFormatted: formatGbp(bio.last30Days)
        },
        {
          kind: 'review',
          label: 'AI reviews',
          count: review.count,
          lifetime: review.lifetime,
          lifetimeFormatted: formatGbp(review.lifetime),
          thisMonth: review.thisMonth,
          thisMonthFormatted: formatGbp(review.thisMonth),
          last30Days: review.last30Days,
          last30DaysFormatted: formatGbp(review.last30Days)
        }
      ],
      // Per-model breakdowns are kept separate per kind so the Spend
      // panel's bar chart (which uses count as denominator) stays
      // well-defined. Reviews get their own sub-section.
      byModel,
      reviewsByModel,
      unknownModelCount: acc.costs.unknownModelCount,
      reviewUnknownModelCount: acc.costs.reviewUnknownModelCount,
      // Convenience scalars for template use — avoid array indexing
      // into byKind from Handlebars, which is brittle.
      reviewsCount: review.count,
      reviewsLifetime: review.lifetime,
      reviewsLifetimeFormatted: formatGbp(review.lifetime),
      biographiesCount: bio.count,
      biographiesLifetime: bio.lifetime,
      biographiesLifetimeFormatted: formatGbp(bio.lifetime)
    },
    activity: {
      thisWeek: acc.activity.thisWeek,
      lastWeek: acc.activity.lastWeek,
      byWeek,
      maxWeekCount: byWeek.reduce(function (max, w) { return Math.max(max, w.count); }, 0)
    },
    flags: {
      pendingReports: acc.flags.pendingReports,
      pendingAcrossRecords: acc.flags.pendingAcrossRecords,
      lifetimeReports: acc.flags.lifetimeReports,
      topReasons: topFlagReasons
    },
    staff: {
      flaggedRecords: acc.staff.flaggedRecords.size,
      notes: acc.staff.notes
    },
    skipReasons: topSkipReasons,

    // v2 pipeline metrics — surfaced on the dashboard's Task 53 panel.
    // Templates read this block directly; keeping it in a top-level
    // `v2` namespace makes it obvious what's the new stuff and lets
    // future tasks add fields without cluttering the v1 shape.
    v2: {
      recordsWithSentences: acc.v2.recordsWithSentences,
      // Sort source-tag distribution most-common first for display.
      // Includes total across all sentences for percentage calculations.
      sourceTagDistribution: sortedSourceTagDistribution(acc.v2.sourceTagCounts),
      sourceTagTotal: Object.keys(acc.v2.sourceTagCounts).reduce(function (sum, k) {
        return sum + acc.v2.sourceTagCounts[k];
      }, 0),
      verificationCandidates: {
        generalKnowledge: acc.v2.verificationCandidates.generalKnowledge,
        contextualising: acc.v2.verificationCandidates.contextualising,
        lowConfidenceInferred: acc.v2.verificationCandidates.lowConfidenceInferred,
        // Total candidates across all three categories.
        total: acc.v2.verificationCandidates.generalKnowledge +
          acc.v2.verificationCandidates.contextualising +
          acc.v2.verificationCandidates.lowConfidenceInferred,
        estimatedExternalValidationCost: acc.v2.verificationCandidates.estimatedExternalValidationCost,
        estimatedExternalValidationCostFormatted: formatGbp(acc.v2.verificationCandidates.estimatedExternalValidationCost)
      },
      recordsWithOpenFindings: acc.v2.recordsWithOpenFindings.size,
      recordsWithCuratorDecisions: acc.v2.recordsWithCuratorDecisions.size
    }
  };
}

function emptyStats () {
  return {
    computedAt: new Date().toISOString(),
    totals: { biographies: 0, live: 0, flagged: 0, hidden: 0, insufficient_data: 0, liveSuppressed: 0, flaggedSuppressed: 0, hiddenFromPublic: 0 },
    subjects: { person: 0, company: 0, organisation: 0, unknown: 0 },
    costs: {
      lifetime: 0,
      lifetimeFormatted: '£0',
      thisMonth: 0,
      thisMonthFormatted: '£0',
      last30Days: 0,
      last30DaysFormatted: '£0',
      byKind: [
        { kind: 'biography', label: 'Biographies', count: 0, lifetime: 0, lifetimeFormatted: '£0', thisMonth: 0, thisMonthFormatted: '£0', last30Days: 0, last30DaysFormatted: '£0' },
        { kind: 'review', label: 'AI reviews', count: 0, lifetime: 0, lifetimeFormatted: '£0', thisMonth: 0, thisMonthFormatted: '£0', last30Days: 0, last30DaysFormatted: '£0' }
      ],
      byModel: [],
      reviewsByModel: [],
      unknownModelCount: 0,
      reviewUnknownModelCount: 0,
      reviewsCount: 0,
      reviewsLifetime: 0,
      reviewsLifetimeFormatted: '£0',
      biographiesCount: 0,
      biographiesLifetime: 0,
      biographiesLifetimeFormatted: '£0'
    },
    activity: { thisWeek: 0, lastWeek: 0, byWeek: [], maxWeekCount: 0 },
    flags: { pendingReports: 0, pendingAcrossRecords: 0, lifetimeReports: 0, topReasons: [] },
    staff: { flaggedRecords: 0, notes: 0 },
    skipReasons: [],
    v2: {
      recordsWithSentences: 0,
      sourceTagDistribution: [],
      sourceTagTotal: 0,
      verificationCandidates: {
        generalKnowledge: 0,
        contextualising: 0,
        lowConfidenceInferred: 0,
        total: 0,
        estimatedExternalValidationCost: 0,
        estimatedExternalValidationCostFormatted: '£0'
      },
      recordsWithOpenFindings: 0,
      recordsWithCuratorDecisions: 0
    },
    unavailable: true
  };
}

// Convert a { source-tag → count } map into a sorted array of { tag,
// count } rows, most-common first. Used by the v2 dashboard panel to
// render the source-tag distribution as a stacked bar / list. Filters
// zero-count entries (a legacy record with an empty sentences[] array
// shouldn't produce a row).
function sortedSourceTagDistribution (map) {
  return Object.keys(map).map(function (tag) {
    return { tag, count: map[tag] };
  }).filter(function (r) { return r.count > 0; })
    .sort(function (a, b) { return b.count - a.count; });
}

// Convert a { modelId → { cost, count } } map into the dashboard's per-
// model row shape, sorted most-used first. Used for both biography and
// review model breakdowns — same shape, different inputs.
function sortedModelBreakdown (byModelMap) {
  return Object.keys(byModelMap).map(function (id) {
    const m = modelsRegistry.getModel(id);
    return {
      id,
      label: m ? m.label : id,
      cost: byModelMap[id].cost,
      costFormatted: formatGbp(byModelMap[id].cost),
      count: byModelMap[id].count
    };
  }).sort(function (a, b) { return b.count - a.count; });
}

const formatGbp = modelsRegistry.formatGbp;

// Pure helpers — kept here so the module has no runtime dependencies beyond
// the models registry.
function isSameCalendarMonth (a, b) {
  return a.getUTCFullYear() === b.getUTCFullYear() && a.getUTCMonth() === b.getUTCMonth();
}

function withinDays (date, days) {
  const diffMs = Date.now() - date.getTime();
  return diffMs >= 0 && diffMs < days * 24 * 60 * 60 * 1000;
}

// ISO weeks start Monday. We use the date (midnight UTC) at the start of
// the week that contains `d`, so bucketing is stable and independent of
// local time zones.
function startOfIsoWeek (d) {
  const date = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  const day = date.getUTCDay() || 7; // Sunday=0 → 7
  if (day !== 1) date.setUTCDate(date.getUTCDate() - (day - 1));
  return date;
}

module.exports = { getStats, invalidate };
